### ISSUE TITLE
Get traffic data for repo A, store in folder in repo B

### ISSUE THREAD

**Issue by egil** [sangonzal/repository-traffic-action#12]
Hi Santiago

First of, this looks really good, great work.

I want to know if it is possible to set up a workflow that will get the traffic data from repo A and store it in repo B, under a specific folder/filename.csv file.

My use case is a bunch of repos that I all want to collect stats for, but I would like to store them in a private repo.

Thanks, Egil

**Comment by sangonzal** [comment]
Hi @egil,  I have never tried to do this. I suspect you might be able to add steps in the workflow to clone repoB from repoA, and commit back to repoB. The place to see if this is possible would be in the checkout and commit actions. 

A simpler way to store stats for multiple repos might be to just to put them in S3 (or your preferred data store). You would run the action from all of your repositories and upload them into the same private S3 bucket.
