### ISSUE TITLE
Does the action overwrite traffic data csvs every time it runs?

### ISSUE THREAD

**Issue by dfmore** [sangonzal/repository-traffic-action#27]
First, thank you for this action - very useful!

In the example this action runs every week. I'm assuming that every time it runs is just overwrites the data it had from the previous week? Or does it work as a log and keeps adding rows to the existing CSV files?

If it overwrites the files, it would be good to mention that in the README. Also, a quick first improvement could be to timestamp each file, so that every week it would generate a file which could be collated into a master.

**Comment by sangonzal** [comment]
Hi @dfmore, when new data is being added to the csv, and the csv already contains data for dates that are being added (like in the scenario that you mentioned), the new dates are merged into the csv by taking the larger value of both. 

For example:
csv: 
01-01-2022  10
01-02-2022  7
01-03-2022  10
01-04-2022  10

New data: 
01-03-2022  10
01-04-2022  14
01-05-2022  5
01-06-2022  5

Final state of csv after action is run:
01-01-2022  10
01-02-2022  7
01-03-2022  10
01-04-2022  14
01-05-2022  5
01-06-2022  5

**Comment by dfmore** [comment]
Thanks 🙏🏽

I tested it and it didn't seem to work, but I must have done something wrong. I've tested it again and it seems to be doing exactly what you described.
